coverage:
  status:
    project:
      unittests:
        flags: unittests
      integration:
        flags: integration
ignore:
  - "**/*StupidSimpleLogger.java"
  - "**/*Runner.java"
  - "**/*InputReadTask.java"
  - "**/*ConsoleUtils.java"