coverage:
  notify:
    after_n_builds: 4
  status:
    project:
      unittests:
        flags: unittests
      integration:
        flags: integration
ignore:
  - "**/*StupidSimpleLogger.java"
  - "**/*Runner.java"
  - "**/*ConsoleUtils.java"