coverage:
  ignore:
    - "**/StupidSimpleLogger.java"
    - "**/ClientRunner.java"
    - "**/ServerRunner.java"
  status:
    project:
      unittests:
        flags: unittests
      integration:
        flags: integration
